FROM introlab3it/rtabmap_ros:humble-latest

RUN apt-get update && apt-get install -y \
    libpcap-dev \
    python3-paho-mqtt \
    ros-humble-controller-manager \
    ros-humble-ros2-control \
    ros-humble-ros2-controllers \
    ros-humble-xacro \
    ros-humble-navigation2 \
    ros-humble-nav2-bringup \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /root/vacop_ws


